import pathlib
pathlib.Path("/Users/amakenzi/Desktop/Dev/yurt/README.md").write_text(
    "# Yurt Coffee - Modern Coffee Ordering System\n\n"
    "A production-ready, mobile-first coffee ordering system.\n\n"
    "## Architecture\n\n"
    "pnpm monorepo managed with Turborepo:\n"
    "- apps/web - Next.js 16 frontend\n"
    "- apps/backend - NestJS 11 API server\n"
    "- packages/shared-types, shared-validation, shared-config\n\n"
    "## Quick Start\n\n"
    "    pnpm install\n"
    "    cp apps/web/.env.example apps/web/.env.local\n"
    "    cp apps/backend/.env.example apps/backend/.env\n"
    "    pnpm dev\n\n"
    "## Scripts\n\n"
    "    pnpm dev           - Start all apps\n"
    "    pnpm dev:web       - Frontend only (:3000)\n"
    "    pnpm dev:backend   - Backend only (:4000)\n"
    "    pnpm build         - Build all\n"
    "    pnpm lint          - Lint all\n"
    "    pnpm type-check    - TypeScript check all\n\n"
    "## Tech Stack\n\n"
    "- Frontend: Next.js 16, React 19, TailwindCSS 4, Zustand\n"
    "- Backend: NestJS 11, Mongoose 9, Passport, Socket.IO\n"
    "- Auth: NextAuth v4 (JWE) + jose cross-domain decryption\n"
    "- Validation: Zod 4\n"
    "- Database: MongoDB\n"
    "- Build: pnpm workspaces + Turborepo\n"
)
print("README written")
